version: '3.8'
name: user-service

services:
  user-service:
    build:
      context: ../user-service-impl
      dockerfile: Dockerfile
    container_name: user-service-app
    depends_on:
      db-migrator:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/common_db?currentSchema=us
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=us
      - SPRING_DATASOURCE_USERNAME=user_admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - backend-net

  db-migrator:
    image: user-service-db
    container_name: user-service-migrator
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/common_db
      - DB_SCHEMA=us
      - DB_LOGIN=user_admin
      - DB_PASSWORD=password
      - CHANGELOG_FILE=db/changelog/db.changelog-master.xml
    networks:
      - backend-net

networks:
  backend-net:
    external: true